version: '3.7'

services:
  localstack:
    image: localstack/localstack:2.2
    # image: localstack/localstack:2.3.0
    ports:
      - 54566:4566
    environment:
      SERVICES: sqs
      DEFAULT_REGION: ap-northeast-1
    volumes:
      - ./ready.d:/etc/localstack/init/ready.d